// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftUOjlDbWYJdtIj2EbvMG5ZCLHNHe-es',
    appId: '1:749184444668:web:2e3b3e534b4ffc9fbfcf79',
    messagingSenderId: '749184444668',
    projectId: 'minimal-social-media-app-10e42',
    authDomain: 'minimal-social-media-app-10e42.firebaseapp.com',
    storageBucket: 'minimal-social-media-app-10e42.appspot.com',
    measurementId: 'G-83H90Y24QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvbSry-ZgCPhIjsL5mdpQ2_Apq6bLNKIs',
    appId: '1:749184444668:android:f5515327378d20e5bfcf79',
    messagingSenderId: '749184444668',
    projectId: 'minimal-social-media-app-10e42',
    storageBucket: 'minimal-social-media-app-10e42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi2Q4fQBI4Q7kinPV_rdcowqNmh8hVcs8',
    appId: '1:749184444668:ios:9705a64190e02b04bfcf79',
    messagingSenderId: '749184444668',
    projectId: 'minimal-social-media-app-10e42',
    storageBucket: 'minimal-social-media-app-10e42.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi2Q4fQBI4Q7kinPV_rdcowqNmh8hVcs8',
    appId: '1:749184444668:ios:49eba22ffaf08beebfcf79',
    messagingSenderId: '749184444668',
    projectId: 'minimal-social-media-app-10e42',
    storageBucket: 'minimal-social-media-app-10e42.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
